import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "@/app/globals.css";
import Providers from "@/app/providers";
import NavBar from "@/components/nav-bar";
import ThemeBackground from "@/components/theme-bg";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kundanaa",
  description: "Generated by Praveen Kumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <Providers>
          <ThemeBackground />
          <NavBar />
          <main className="w-full px-5">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
