import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./(components)/nav-bar";
import Providers from "./providers";
import DarkVeil from "@/app/(components)/ui/DarkVeil"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kundanaa",
  description: "Generated by Praveen Kumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <Providers>
          <NavBar />
          <div className="absolute inset-0 top-0 z-[-1] min-h-screen" >
            <DarkVeil />
          </div>
          <main className="w-full px-5">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
