import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "@/app/globals.css";
import Providers from "@/app/providers";
import NavBarSection from "@/components/nav-bar";
// import ThemeBackground from "@/components/theme-bg";
import FooterSection from "@/components/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kundanaa",
  description: "Generated by Praveen Kumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <Providers>
          {/* <div className="fixed left-0 top-0 -z-10 h-full w-full" suppressHydrationWarning>
            <ThemeBackground />
          </div> */}
          <div className="relative mx-auto h-screen w-full max-w-7xl md:px-8 lg:px-12 flex flex-col justify-between">
            <NavBarSection />
            <main className="flex-1 w-full mb-auto">
              {children}
            </main>
            <FooterSection />
          </div>
        </Providers>
      </body>
    </html>
  );
}
